# Generated by Django 3.2.4 on 2021-06-11 03:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0005_alter_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='1080x1080'),
        ),
    ]
